version: '3.3'

services:
  nodejs:
    image: testnodejs
    ports:
     - "3050:3050"
     - "8081:8080"
    networks:
     - proxy
    deploy:
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.nodejs.rule=Host(`nodejs.ddnsking.com`) && Path(`/api`)"
          - "traefik.http.routers.nodejs.tls=true"
          - "traefik.http.routers.nodejs.tls.certresolver=default"
          - "traefik.http.routers.nodejs.entryPoints=web"
          - "traefik.http.routers.nodejs.service=nodejs-service"
          - "traefik.http.services.nodejs-service.loadbalancer.server.port=3050"
          - "traefik.docker.network=proxy"



networks:
    proxy:
       external: true
